import { rgb } from "pdf-lib";

import { createPDFBuilder } from "@/lib/pdf/builder";
import { createServerClient } from "@/lib/db/supabase-server";

export async function POST(request: Request) {
  try {
    const supabase = await createServerClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return Response.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { notesContent, subjectName, topicName } = await request.json();

    if (!notesContent) {
      return Response.json({ error: "No content" }, { status: 400 });
    }

    const dateStr = new Date().toLocaleDateString("en-IN", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });

    const { builder } = await createPDFBuilder();

    builder.addPageHeader(
      "Quick Notes",
      topicName ?? subjectName ?? "Quick Notes",
      `${subjectName ?? ""}  ·  Generated ${dateStr}`
    );

    builder.space(8);

    // Render the full markdown notes
    builder.markdown(notesContent, 11);

    builder.space(16);
    builder.drawLine();
    builder.space(4);
    builder.text("Generated by EduNexus AI", {
      size: 9,
      color: rgb(0.58, 0.635, 0.71),
      align: "center",
    });

    const pdfBytes = await builder.build();
    return new Response(Buffer.from(pdfBytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="quick-notes.pdf"`,
      },
    });
  } catch (err) {
    console.error("[notes/export]", err);
    return Response.json({ error: "Export failed" }, { status: 500 });
  }
}

