import { rgb } from "pdf-lib";

import {
  COLORS,
  createPDFBuilder,
  extractDiagramBlocks,
  fetchMermaidAsPng,
  svgCodeToPngBytes,
} from "@/lib/pdf/builder";
import { createServerClient } from "@/lib/db/supabase-server";
import { requireAuth, requireRole, apiError, apiSuccess } from "@/lib/api/helpers";

export async function POST(request: Request) {
  try {
    const authResult = await requireAuth();
    if (authResult instanceof Response) return authResult;
    const { user, supabase } = authResult;

    const { notesContent, subjectName, topicName } = await request.json();

    if (!notesContent) {
      return apiError("No content", 400);
    }

    const dateStr = new Date().toLocaleDateString("en-IN", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });

    const { builder } = await createPDFBuilder();

    builder.addPageHeader(
      "Quick Notes",
      topicName ?? subjectName ?? "Quick Notes",
      `${subjectName ?? ""}  ·  Generated ${dateStr}`
    );

    builder.space(8);

    const parts = extractDiagramBlocks(String(notesContent));
    for (const part of parts) {
      if (part.type === "text") {
        if (part.content.trim()) {
          builder.markdown(part.content, 11);
        }
      } else if (part.type === "mermaid") {
        const pngBytes = await fetchMermaidAsPng(part.content);
        if (pngBytes) {
          await builder.addImage(pngBytes, "Diagram");
        } else {
          builder.text("[Diagram — open in EduNexus AI to view]", {
            size: 10,
            color: COLORS.light,
          });
        }
      } else {
        const pngBytes = await svgCodeToPngBytes(part.content);
        if (pngBytes) {
          await builder.addImage(pngBytes, "Diagram");
        } else {
          builder.text("[Diagram — open in EduNexus AI to view]", {
            size: 10,
            color: COLORS.light,
          });
        }
      }
    }

    builder.space(16);
    builder.drawLine();
    builder.space(4);
    builder.text("Generated by EduNexus AI", {
      size: 9,
      color: rgb(0.58, 0.635, 0.71),
      align: "center",
    });

    const pdfBytes = await builder.build();
    return new Response(Buffer.from(pdfBytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="quick-notes.pdf"`,
      },
    });
  } catch (err) {
    console.error("[notes/export]", err);
    return apiError("Export failed", 500);
  }
}

