import type { NextRequest } from "next/server";

import { createPDFBuilder } from "@/lib/pdf/builder";
import { createServerClient } from "@/lib/db/supabase-server";
import { rgb } from "pdf-lib";

export async function POST(request: NextRequest) {
  try {
    const supabase = await createServerClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return Response.json({ error: "Unauthorized" }, { status: 401 });
    }

    const {
      moduleLabel,
      score,
      correctAnswers,
      totalQuestions,
      mastery,
      masteryMessage,
      questionAnalysis,
      timeTaken,
    } = await request.json();

    const safeQuestionAnalysis: any[] = Array.isArray(questionAnalysis)
      ? questionAnalysis
      : [];

    const { builder } = await createPDFBuilder();

    builder.addPageHeader(
      "Practice Session Report",
      String(moduleLabel ?? ""),
      `${new Date().toLocaleDateString("en-IN", {
        day: "numeric",
        month: "long",
        year: "numeric",
      })} - ${correctAnswers}/${totalQuestions} correct`
    );

    const masteryColor =
      mastery === "mastered"
        ? rgb(0.086, 0.639, 0.290)
        : mastery === "progressing"
          ? rgb(0.145, 0.388, 0.922)
          : mastery === "developing"
            ? rgb(0.855, 0.475, 0.027)
            : rgb(0.863, 0.196, 0.184);

    builder.space(8);
    builder.text(`${score}% - ${String(mastery).toUpperCase()}`, {
      font: builder.getFont("bold"),
      size: 18,
      color: masteryColor,
    });
    builder.space(4);
    builder.text(String(masteryMessage ?? ""), {
      size: 11,
      color: rgb(0.278, 0.337, 0.424),
    });
    builder.space(8);
    builder.drawLine();

    builder.sectionHeading(
      `Question Review (${safeQuestionAnalysis.length} questions)`
    );
    builder.space(4);

    for (let i = 0; i < safeQuestionAnalysis.length; i++) {
      const q = safeQuestionAnalysis[i];
      builder.ensureSpace(100);
      builder.space(10);

      const qColor = q.isCorrect
        ? rgb(0.086, 0.639, 0.290)
        : rgb(0.863, 0.196, 0.184);

      builder.text(
        `Q${i + 1} [${
          String(q.difficulty_level ?? "intermediate").toUpperCase()
        }]  ${q.isCorrect ? "[OK] Correct" : "[X] Wrong"}`,
        {
          font: builder.getFont("bold"),
          size: 10,
          color: qColor,
        }
      );
      builder.space(2);
      builder.text(String(q.question ?? ""), {
        font: builder.getFont("bold"),
        size: 11,
        color: rgb(0.118, 0.161, 0.235),
      });
      builder.space(3);

      if (Array.isArray(q.options)) {
        const optLabels = ["A", "B", "C", "D"];
        for (let j = 0; j < q.options.length; j++) {
          const label = optLabels[j] ?? String(j + 1);
          const optText = String(q.options[j] ?? "").replace(
            /^[A-D]\.\s*/i,
            ""
          );

          const isCorrectOpt = String(q.correctAnswer ?? "") === label;
          const isStudentChoice = String(q.studentAnswer ?? "") === label;

          const optColor = isCorrectOpt
            ? rgb(0.086, 0.639, 0.290)
            : isStudentChoice && !q.isCorrect
              ? rgb(0.863, 0.196, 0.184)
              : rgb(0.278, 0.337, 0.424);

          const prefix = isCorrectOpt
            ? "[OK]"
            : isStudentChoice && !q.isCorrect
              ? "[X]"
              : "o";

          builder.text(`${prefix}  ${label}. ${optText}`, {
            size: 10.5,
            color: optColor,
            x: 60,
          });
        }
      }

      builder.space(3);
      if (q.explanation) {
        builder.text(`Explanation: ${q.explanation}`, {
          size: 10,
          color: rgb(0.278, 0.337, 0.424),
          x: 60,
        });
      }

      if (i < safeQuestionAnalysis.length - 1) {
        builder.space(6);
        builder.drawLine(rgb(0.886, 0.914, 0.941), 0.5);
      }
    }

    builder.space(16);
    builder.drawLine();
    builder.space(4);
    builder.text("Generated by EduNexus AI - Practice Engine", {
      size: 9,
      color: rgb(0.580, 0.635, 0.710),
      align: "center",
    });

    // builder.build() returns Uint8Array
    const pdfBytes = await builder.build();
    return new Response(Buffer.from(pdfBytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="practice-${String(
          moduleLabel ?? "module"
        )}-report.pdf"`,
      },
    });
  } catch (err) {
    console.error("[placement/practice/export] error:", err);
    return Response.json({ error: "Export failed" }, { status: 500 });
  }
}

